export const card_data=[
    {
        "title":"Abacus",
        "imageCode":1,
        "imageInvalid":"couldn't find the image",
        "description":"Abacus aims to develop brain by helping you improve your calculations, abilities, and mental arithmetic",
        "tags":["Walkers","Joggers","Sprinters"],
        "css":"w-full h-3/5",
    },
    {        
        "title":"Rubik's Cube",
        "imageCode":2,
        "imageInvalid":"couldn't find the image",
        "description":"Learn to solve different types of Rubick's Cubes in simpler way which sharpen your mind",
        "tags":["2x2 Cube","3x3 Cube","4x4 Cube"],
        "css":"w-full h-3/5",
    },
    {
        "title":"Vedic Maths",
        "imageCode":5,
        "imageInvalid":"couldn't find the image",
        "description":"Vedic Maths Will Enable You To Calculate Much Faster Compared To Conventional System",
        "tags":["Level 1","Level 2"],
        "css":"w-full h-3/5",
    },
    {
        "title":"Calligraphy",
        "imageCode":3,
        "imageInvalid":"couldn't find the image",
        "description":"Learn Calligraphy from one of our many classes, both hand drawn and digital",
        "tags":[],
        "css":"w-full h-3/5",
    },
    {
        "title":"Hand Writing",
        "imageCode":4,
        "imageInvalid":"couldn't find the image",
        "description":"Improve your handwriting with fauxligraphy tools, water brush, pen and ink",
        "tags":[],
        "css":"w-full h-3/5",
    },
    {
        "title":"Coming Soon",
        "imageCode":4,
        "imageInvalid":"",
        "description":"We are including new courses gradually. Watch this space for updates",
        "tags":[],
        "css":"w-full h-3/5",
    },
        
]