export const card_data=[
    {
        "title":"Abacus",
        "imageCode":1,
        "imageInvalid":"couldn't find the image",
        "description":"Abacus aims to develop brain by helping you improve your calculations, mental arithmetic abilities",
        "tags":[],//["Walkers","Joggers","Sprinters"],
        "css":"w-full h-3/5",
        "headCount":21,
        "gradCount":16,
        "rating":4.7,
    },
    {        
        "title":"Rubik's Cube",
        "imageCode":2,
        "imageInvalid":"couldn't find the image",
        "description":"Learn to solve various types of Rubik's Cubes in simpler way which sharpen your mind",
        "tags":[],//["2x2 Cube","3x3 Cube","4x4 Cube"],
        "css":"w-full h-3/5",
        "headCount":16,
        "gradCount":9,
        "rating":4.5,
    },
    {
        "title":"Vedic Maths",
        "imageCode":5,
        "imageInvalid":"couldn't find the image",
        "description":"Vedic Maths Will Enable You To Calculate Much Faster Compared To Conventional System",
        "tags":[],//["Level 1","Level 2"],
        "css":"w-full h-3/5",
        "headCount":18,
        "gradCount":10,
        "rating":4.7,
    },
    {
        "title":"Calligraphy",
        "imageCode":3,
        "imageInvalid":"couldn't find the image",
        "description":"Learn Calligraphy from one of our many classes, both hand drawn and digital",
        "tags":[],
        "css":"w-full h-3/5",
        "headCount":9,
        "gradCount":6,
        "rating":4.4,
    },
    {
        "title":"Hand Writing",
        "imageCode":4,
        "imageInvalid":"couldn't find the image",
        "description":"Improve your handwriting with fauxligraphy tools, water brush, pen and ink",
        "tags":[],
        "css":"w-full h-3/5",
        "headCount":12,
        "gradCount":7,
        "rating":4.6,
    },
    {
        "title":"Coming Soon",
        "imageCode":4,
        "imageInvalid":"",
        "description":"We are including new courses gradually. Watch this space for updates",
        "tags":[],
        "css":"w-full h-3/5",
    },
        
]